### ISSUE TITLE
Test userstory

### ISSUE THREAD

**Issue by poyrakie** [ECProjectGroup5/ProjectGroupFive#11]
**Tasks**
- [ ] Skapa ett formulär för att registrera en ny produkt.
- [ ] Lägg till fält för:
- [ ] Produktnamn
- [ ] Beskrivning
- [ ] Pris
- [ ] Rabatterat pris
- [ ] Kategori 
- [ ] Lagerstatus (kopplad till separat tabell)
- [ ] URL till produktbild.
- [ ] Lägga till fält för Produktspecifika värden/info vid behov
- [ ] Lägg till en knapp för att skicka formuläret.
- [ ] Testa att alla fält visas och fungerar korrekt.

**Acceptanskriterier**

- [ ] Formuläret ska innehålla alla specificerade fält för produktinformation, inklusive namn, beskrivning, pris, kategori, lagerstatus, och bild-URL.
- [ ] Admin ska kunna utöka produktformulär utefter produktens egenskaper och behov
- [ ] Alla fält ska vara validerade och dynamiska vid behov.

**Testfallsbeskrivnig**
- [ ] Formuläret ska testas för korrekt visning, funktionalitet och användarvänlighet i olika miljöer.

**Aktivitetsdiagram gjort av Jacob**

![Image](https://github.com/user-attachments/assets/a0725d71-73f7-4bc6-8e8c-baa28573dc6c)

@startuml
:Admin;
start

:Skapa formulär för produktregistrering;

:Ange fält för produktnamn;
:Ange fält för beskrivning;
:Ange fält för pris;
:Ange fält för rabatterat pris;
:Ange fält för kategori;
:Ange fält för lagerstatus (kopplad till separat tabell);
:Ange fält för URL till produktbild;

:Skapa möjlighet att lägga till fält för produktspecifika värden;

:Ange en knapp för att skicka formuläret;

:Testa att alla fält visas och fungerar korrekt;

stop
@enduml

**Sekvensdiagram**

```mermaid
sequenceDiagram
participant Admin
participant Frontend

Admin->>Frontend: Öppnar produktregistreringsformulär
Frontend->>Admin: Visar formulär med fält för produktinformation
Admin->>Frontend: Fyller i fält (namn, beskrivning, pris, kategori, lagerstatus, bild-URL)
Frontend->>Admin: Dynamiskt validerar obligatoriska fält
Admin->>Frontend: Lägger till produktspecifika värden (om behov finns)
Frontend->>Admin: Visar utökade fält vid behov
Admin->>Frontend: Klickar på skicka-knappen
Frontend->>Admin: Visar validering av fälten och eventuella felmeddelanden
