### ISSUE TITLE
33. Användare: Implementera funktion för att visa alla produkter

### ISSUE THREAD

**Issue by kajsaramstrom** [ECProjectGroup5/ProjectGroupFive#15]
**Tasks**
- [x] Skapa en vy som listar alla produkter med relevant information (namn, pris, lagerstatus, etc.).
- [x] Skapa funktion för att hämta samtliga sparade produkter via API.
- [ ] Implementera paginering/sliders eller dylikt om det finns många produkter.
- [ ] Testa att alla produkter visas korrekt i listan.

**Acceptanskriterier**

- [ ]  Produktlista: En vy ska skapas som listar alla produkter i systemet. För varje produkt ska relevant information visas, inklusive namn, pris, lagerstatus och andra viktiga detaljer som produktkategori och eventuell rabatterad prisinformation.
- [ ]  Paginering: Om det finns ett stort antal produkter (t.ex. fler än 20), ska paginering implementeras för att undvika överladdning av sidan. Användare ska kunna navigera mellan olika sidor av produktlistan.
- [ ]  Test av korrekt visning: Testa att alla produkter visas korrekt med sin tillhörande information. Verifiera att produktnamn, pris och lagerstatus är korrekta för varje produkt.
- [ ]  Test av paginering: Om det finns många produkter, testa att pagineringen fungerar korrekt och att admin kan bläddra igenom alla produkter utan problem.

**Testfallsbeskrivning**

- [ ] Öppna vyn som listar alla produkter och verifiera att alla produkter visas korrekt med sitt namn, pris, lagerstatus och övrig relevant information.
- [ ] Kontrollera att inga produkter saknas i listan och att all information är korrekt (t.ex. att pris och lagerstatus stämmer överens med databasen).
- [ ] Om det finns fler än 20 produkter, kontrollera att paginering är implementerad och att användare kan bläddra mellan olika sidor av produktlistan.
- [ ] Verifiera att varje sida av listan laddas korrekt och att rätt antal produkter visas på varje sida (t.ex. 20 produkter per sida).
- [ ] Om sortering eller filtrering är tillgängligt, testa att sorteringen fungerar korrekt efter namn, pris eller lagerstatus. Kontrollera att produkterna visas i rätt ordning.
- [ ] Testa att filtrering fungerar och att endast produkter som matchar det valda filtret visas (t.ex. filtrera på kategori eller lagerstatus).
- [ ] Verifiera att varje produkt i listan visar rätt namn, pris, och lagerstatus, och att det inte finns några fel i visningen av denna information.
- [ ] Om det inte finns några produkter, verifiera att vyn hanterar detta och visar ett meddelande om att inga produkter finns tillgängliga.

![Image](https://github.com/user-attachments/assets/176fd38a-e203-4911-8de7-a641c117f8d3)

@startuml UserStory33
title Som Användare vill jag kunna se samtliga produkter
start
skinparam Style strictuml
skinparam monochrome reverse
skinparam SequenceMessageAlignment center

:Användaren navigerar till produktsidan;

:Frontend skickar GET-anrop till backend för att hämta alla produkter;

:Backend tar emot begäran och hämtar produktdata från databasen;

:Databasen returnerar en lista med alla produkter;

:Backend skickar listan över produkter till frontend (inklusive namn, pris, lagerstatus, etc.);

:Frontend visar produktlistan till Användaren;

if (Finns fler än 20 produkter?) then (Ja)
:Frontend visar pagineringselement;

while (Användaren navigerar mellan sidor)

    :Frontend visar produkterna för den valda sidan;
endwhile
else (Nej)
:Visar alla produkter på en sida;
endif

stop
@enduml
